web_application/Controllers/TemasController.cs
using BLL;
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web_application.Controllers
{
    public class TemasController : Controller
    {
        // GET: Categorias
        public ActionResult Index()
        {
            TemasBLL oBLL = new TemasBLL();
            List<Tema> temas = oBLL.RetrieveAll();
            return View(temas);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tema tema)
        {
            ActionResult Result;
            try
            {
                if (ModelState.IsValid)
                {
                    TemasBLL oBLL = new TemasBLL();
                    oBLL.Create(tema);
                    Result = RedirectToAction("Index");
                }
                else
                {
                    Result = View(tema);
                }
                return Result;
            }
            catch (Exception e)
            {
                return View(tema);
            }
        }

        public ActionResult Edit(int id)
        {
            TemasBLL oBLL = new TemasBLL();
            Tema tema = oBLL.Retrieve(id);

            return View(tema);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tema tema)
        {
            ActionResult Result;
            try
            {
                if (ModelState.IsValid)
                {
                    TemasBLL oBLL = new TemasBLL();
                    oBLL.Update(tema);
                    Result = RedirectToAction("Index");
                }
                else
                {
                    Result = View(tema);
                }
                return Result;
            }
            catch (Exception e)
            {
                return View(tema);
            }
        }

        public ActionResult Details(int id)
        {
            TemasBLL oBLL = new TemasBLL();
            Tema tema = oBLL.Retrieve(id);

            return View(tema);
        }

        public ActionResult Delete(int id)
        {
            TemasBLL oBLL = new TemasBLL();
            oBLL.Delete(id);
            return RedirectToAction("Index"); //redirecionar al index cuando borres
        }
    }
}

web_application/Views/Temas/Create.cshtml
@model Entities.Tema

@{
    ViewBag.Title = "Nuevo Tema";
}




<div class="row">
    <div class="col-md-12">
        <!-- BEGIN VALIDATION STATES-->
        <div class="portlet light portlet-fit portlet-form bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-child" aria-hidden="true"></i>
                    <span class="caption-subject font-dark sbold uppercase">Creación de un tema</span>
                </div>
                @*<div class="actions">
                        <div class="btn-group btn-group-devided" data-toggle="buttons">
                            <label class="btn btn-transparent dark btn-outline btn-circle btn-sm active">
                                <input type="radio" name="options" class="toggle" id="option1">Actions
                            </label>
                            <label class="btn btn-transparent dark btn-outline btn-circle btn-sm">
                                <input type="radio" name="options" class="toggle" id="option2">Settings
                            </label>
                        </div>
                    </div>*@
            </div>
            <div class="portlet-body">
                <!-- BEGIN FORM-->
                @using (Html.BeginForm("Create", "Temas", null, FormMethod.Post, new { id = "form_sample_3", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    @*<form action="#" id="form_sample_3" class="form-horizontal">*@
                    <div class="form-body">
                        <div class="alert alert-danger display-hide">
                            <button class="close" data-close="alert"></button> Parece que tienes problemas, revisa los campos.
                        </div>
                        <div class="alert alert-success display-hide">
                            <button class="close" data-close="alert"></button> Formulario exitoso
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.NombreTema, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.NombreTema, new { htmlAttributes = new { @class = "form-control", required = "required", name = "name" } })
                                @Html.ValidationMessageFor(model => model.NombreTema, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn green-sharp btn-circle" data-toggle="confirmation" data-popout="true">Crear tema</button>
                                </div>
                            </div>
                        </div>
                    </div>
                            }
            </div>
        </div>
    </div>
</div>

<button class="btn red btn-circle btn-outline sbold uppercase mt-sweetalert" data-title="La contraseña no coincide" data-message="Parece que tienes problemas" data-type="error" data-allow-outside-click="true"
        data-confirm-button-class="btn-danger" id="alerta" style='display:none;'>
    Parece que tienes problemas
</button>

@section Styles{
    <link href="~/Content/select2.css" rel="stylesheet" />
    <link href="~/Content/select2-bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-wysihtml5.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-markdown.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/sweetalert.css" rel="stylesheet" />
    @*<link href="~/Content/components-rounded-rtl.min.css" rel="stylesheet" />
        <link href="~/Content/plugins-rtl.min.css" rel="stylesheet" />*@
    @*<link href="~/Content/layout-rtl.min.css" rel="stylesheet" />
        <link href="~/Content/custom-rtl.min.css" rel="stylesheet" />*@

}

@section Scripts {



    <script src="~/Scripts/select2.full.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/additional-methods.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js" type="text/javascript"></script>
    <script src="~/Scripts/wysihtml5-0.3.0.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap-wysihtml5.js" type="text/javascript"></script>
    <script src="~/Scripts/ckeditor.js" type="text/javascript"></script>
    <script src="~/Scripts/markdown.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap-markdown.js" type="text/javascript"></script>
    <script src="~/Scripts/form-validation.js" type="text/javascript"></script>

    <script src="~/Scripts/bootstrap-confirmation.min.js"></script>
    <script src="~/Scripts/ui-confirmations.min.js"></script>

    <script src="~/Scripts/sweetalert.min.js"></script>
    <script src="~/Scripts/ui-sweetalert.min.js"></script>


    <script src="~/Scripts/piexif.js"></script>
    <script src="~/Scripts/piexif.min.js"></script>
    <script src="~/Scripts/purify.js"></script>
    <script src="~/Scripts/sortable.js"></script>
    <script src="~/Scripts/sortable.min.js"></script>
    <script src="~/Scripts/purify.min.js"></script>
    <script src="~/Scripts/fileinput.min.js"></script>
    <script src="~/Scripts/es.js"></script>
    <script src="~/Scripts/theme.min.js"></script>
    <script type="text/javascript">
        $('#upFile').fileinput({
            theme: 'fa',
            language: 'es',
            showUpload: false,
            maxFileSize: 3000,
            maxFilesNum: 1,
            allowedFileExtensions: ['jpg', 'png']
        });

    </script>

    <script type="text/javascript">
        function valideteform() {
            var contra1 = document.getElementById("register_password").value;
            var contra2 = document.getElementById("register_password2").value;
            if (contra1 == contra2) {

                return true;

            } else {
                $("#alerta").click();
                return false;
            }
        }
    </script>





}

web_application/Views/Temas/Details.cshtml
@model Entities.Tema
@{
    ViewBag.Title = "Detalles";
}

<h2>Tema: @Model.NombreTema</h2>


<a class="btn red btn-outline sbold" data-toggle="modal" href="#basic">
    <icon class="fa fa-trash"></icon> Eliminar
</a>

<a href="@Url.Action("Delete", "Temas",new { id=Model.TemaID})" id="borrar_link" style='display:none;'>
    <icon class="fa fa-info"></icon> Borrar
</a>


<!-- /.modal-content -->
<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Borrar cuenta</h4>
            </div>
            <div class="modal-body">¿Seguro de eliminar el tema <b>@Model.NombreTema </b> ? </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-md-6">
                        <button type="button" class="btn dark btn-outline" data-dismiss="modal">No</button>
                        <button type="button" id="borrar" class="btn red" onclick="borrar()">Borrar</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

@section Styles{
    <link href="~/Content/bootstrap-table.min.css" rel="stylesheet" />

}

@section Scripts {
    <script src="~/Scripts/bootstrap-table.min.js"></script>
    <script src="~/Scripts/table-bootstrap.min.js"></script>

    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/ui-modals.min.js"></script>

    <script type="text/javascript">
        //acciones automaticas al cargar la pagina

        function borrar() {
            $("#borrar_link")[0].click();
        }
    </script>
}

web_application/Views/Temas/Edit.cshtml
@model Entities.Tema

@{
    ViewBag.Title = "Editar Tema";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tema</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TemaID)

        <div class="form-group">
            @Html.LabelFor(model => model.NombreTema, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreTema, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreTema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

web_application/Views/Temas/Index.cshtml
@model IEnumerable<Entities.Tema>

@{
    ViewBag.Title = "Lista de Temas";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-social-dribbble font-green hide"></i>
                    <span class="caption-subject font-dark bold uppercase">Temas</span>
                </div>
                <div class="actions">
                     <a href="@Url.Action("Create", "Temas")" class="btn btn-outline btn-circle green-meadow btn-sm">
                        <icon class="fa fa-plus"></icon> Agregar
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <table data-toggle="table" data-url="../assets/global/plugins/bootstrap-table/data/data1.json" data-height="299" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true">
                    <thead>
                        <tr>
                            <th data-field="id" data-align="right">Nombre</th>
                            <th data-field="name" data-align="center">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NombreTema)
                                </td>

                                <td>

                                    <a href="@Url.Action("Details", "Temas",new {id=item.TemaID})" class="btn btn-circle red btn-sm">
                                        <icon class="fa fa-trash"></icon> Eliminar
                                    </a>

                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
    </div>
    @section Styles{
        <link href="~/Content/bootstrap-table.min.css" rel="stylesheet" />

    }

    @section Scripts {
        <script src="~/Scripts/bootstrap-table.min.js"></script>
        <script src="~/Scripts/table-bootstrap.min.js"></script>

<script src="~/Scripts/jquery-ui.min.js"></script>
<script src="~/Scripts/ui-modals.min.js"></script>

        <script type="text/javascript">
                //acciones automaticas al cargar la pagina
              
                function borrar() {
                    $("#borrar_link")[0].click();
                }
        </script>
    }