web_application/Controllers/PreguntasController.cs
using web_application.Models;
using BLL;
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web_application.Controllers
{
    public class PreguntasController : Controller
    {
        // GET: Preguntas
        // GET: Categorias
        public ActionResult Index()
        {
            PreguntasBLL oBLL = new PreguntasBLL();
            List<Pregunta> preguntas = oBLL.RetrieveAll();
            return View(preguntas);
        }

        public ActionResult CreateSelect()
        {
            TemasBLL mBLL = new TemasBLL();
            List<Tema> tema = mBLL.RetrieveAll();
            List<SelectListItem> listSelect = new List<SelectListItem>();
            foreach (var tem in tema)
            {
                SelectListItem selectListItem = new SelectListItem()
                {
                    Text = tem.NombreTema,
                    Value = tem.TemaID.ToString(),
                    Selected = tem.IsSelected

                };
                listSelect.Add(selectListItem);

            }

            VMPregunta vMPregunta = new VMPregunta();
            vMPregunta.Temas = listSelect;
            return PartialView("_Select", vMPregunta);
        }

        public ActionResult Create()
        {
            UsuariosBLL obBLL = new UsuariosBLL();
            List<Usuario> usuarios = obBLL.RetrieveAll();
            ViewBag.UsuarioID = new SelectList(usuarios, "UsuarioID", "UserName");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pregunta pregunta, VMPregunta vMPregunta)
        {
            var selectedTemas = vMPregunta.SelectedTemas;

            ActionResult Result;
            try
            {

                if (selectedTemas != null)
                {

                    foreach (var temaid in selectedTemas)
                    {
                        PreguntaTemasBLL mBLL = new PreguntaTemasBLL();
                        PreguntaTema tema = new PreguntaTema();
                        tema.TemaID = int.Parse(temaid);
                        tema.PreguntaID = pregunta.PreguntaID;
                        pregunta.PreguntaTemas.Add(tema);
                    }

                }
                if (ModelState.IsValid)
                {
                    PreguntasBLL oBLL = new PreguntasBLL();
                    oBLL.Create(pregunta);
                    return RedirectToAction("Index");
                }
                else
                {
                    Result = View(pregunta);
                }
                return Result;
            }
            catch (Exception e)
            {
                return View(pregunta);
            }
        }

        public string GetTema(int id)
        {
            TemasBLL mBLL = new TemasBLL();
            Tema tema = mBLL.Retrieve(id);
            var name = tema.NombreTema;

            return name;
        }
        public string GetTemas(int id)
        {
            TemasBLL mBLL = new TemasBLL();
            Tema tema = mBLL.Retrieve(id);
            var name = tema.NombreTema;

            return name;
        }
        public ActionResult ShowTemas(int id)
        {
      

            PreguntaTemasBLL preguntasBLL = new PreguntaTemasBLL();
            List<PreguntaTema> pregBLL = preguntasBLL.FilterPreguntasTemaByID(id);
            return PartialView("_ShowTemas",pregBLL);

        }

        public ActionResult Edit(int id)
        {
            PreguntasBLL oBLL = new PreguntasBLL();
            Pregunta pregunta= oBLL.Retrieve(id);

            return View(pregunta);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pregunta pregunta)
        {
            ActionResult Result;
            try
            {
                if (ModelState.IsValid)
                {
                    PreguntasBLL oBLL = new PreguntasBLL();
                    oBLL.Update(pregunta);
                    Result = RedirectToAction("Index");
                }
                else
                {
                    Result = View(pregunta);
                }
                return Result;
            }
            catch (Exception e)
            {
                return View(pregunta);
            }
        }

        public ActionResult Details(int id)
        {
            PreguntasBLL oBLL = new PreguntasBLL();
            Pregunta pregunta= oBLL.Retrieve(id);
            ViewBag.PreguntaID = id;

            return View(pregunta);
        }

        public ActionResult Delete(int id)
        {
            PreguntasBLL oBLL = new PreguntasBLL();
            oBLL.Delete(id);
            return RedirectToAction("Index"); //redirecionar al index cuando borres
        }
        

        //Guarda y muesta la respuesta recien actualizada 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRespuesta(Pregunta pregunta)
        {

            ViewBag.PreguntaID = pregunta.PreguntaID;
            return View();
        }
        public ActionResult ShowRespuestas(int id)
        {
            RespuestasBLL listBLL = new RespuestasBLL();
            List<Respuesta> respuestas = listBLL.FilterRespuestasByPreguntaID(id);
            return PartialView("_ShowRespuestas",respuestas);
        }

        public ActionResult ShowRespuestasAbreviadas(int id)
        {
            RespuestasBLL listBLL = new RespuestasBLL();
            List<Respuesta> respuestas = listBLL.FilterRespuestasByPreguntaID(id);
            return PartialView("_ShowRespuestasAbreviadas", respuestas);
        }
        public ActionResult ShowNewRespuesta(Pregunta pregunta,Respuesta respuesta)
        {
            ActionResult Result;
            try
            {
                if (ModelState.IsValid)
                {
                    RespuestasBLL oBLL = new RespuestasBLL();
                    oBLL.Create(respuesta);
                    RespuestasBLL listBLL = new RespuestasBLL();
                    List<Respuesta> respuestas = listBLL.FilterRespuestasByPreguntaID(pregunta.PreguntaID);        
                    Result = PartialView("_ShowNewRespuesta",respuestas );
                }
                else
                {
                    Result = View(respuesta);
                }
                return Result;
            }
            catch (Exception e)
            {
                return View(respuesta);
            }


        }
        public ActionResult BuscarPreguntasPorTema(Tema tema)
        {
            PreguntaTemasBLL preguntasBLL = new PreguntaTemasBLL();
            List<PreguntaTema> pregBLL = preguntasBLL.FilterPreguntasporTema(tema.TemaID);
            List<int> preguntasid = new List<int>();
            foreach (var  preg in pregBLL)
            {
                preguntasid.Add(preg.PreguntaID);
            };
            PreguntasBLL oBLL = new PreguntasBLL();
            List<Pregunta> preguntas = new List<Pregunta>();
            foreach( var item in preguntasid)
            {
                PreguntasBLL dBLL = new PreguntasBLL();
                preguntas.Add(dBLL.Retrieve(item));
            };

            return PartialView("_BuscarPreguntasPorTema",preguntas);
        }
        public ActionResult BuscarPreguntas()
        {
            TemasBLL obBLL = new TemasBLL();
            List<Tema> temas = obBLL.RetrieveAll();
            ViewBag.TemaID = new SelectList(temas, "TemaID", "NombreTema");
            return View();

        }
        //controladores de RannFerii////////////////////////////////////////////////////////////////////////////////7
        public ActionResult IndexNotificacion(int id)
        {

            PreguntasBLL oBLL = new PreguntasBLL();
            List<Pregunta> preguntas = oBLL.RetrieveAll();
            ViewBag.notificacion = id;
            return View(preguntas);

        }

        public string Getusuario(int id)
        {
            UsuariosBLL mBLL = new UsuariosBLL();
            Usuario usuario = mBLL.Retrieve(id);
            var name = usuario.UserName;

            return name;
        }

    }
}

web_application/Controllers/UsuariosController.cs
using BLL;
using Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace web_application.Controllers
{
    public class UsuarioController : Controller
    {
        class Global
        {
            public static int suces = 0;

        }

        // GET: Usuario
        [Authorize(Roles = "A")]
        public ActionResult Index()
        {
            UsuariosBLL oBLL = new UsuariosBLL();
            List<Usuario> usuarios = oBLL.RetrieveAll();
            return View(usuarios);
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuario usuario, HttpPostedFileBase upFile)
        {
            ActionResult Result;
            try
            {
                if (ModelState.IsValid)
                {
                    if (upFile != null && upFile.ContentLength > 0)
                    {
                        int tamaño = upFile.ContentLength;
                        byte[] buffer = new byte[tamaño];
                        upFile.InputStream.Read(buffer, 0, tamaño);
                        usuario.Foto = buffer;
                    }
                    UsuariosBLL oBLL = new UsuariosBLL();
                    oBLL.Create(usuario);
                    Result = RedirectToAction("Index");
                }
                else
                {
                    Result = View(usuario);
                }
                return Result;
            }
            catch (Exception e)
            {
                return View(usuario);
            }
        }
        public ActionResult Edit(int id)
        {
            UsuariosBLL oBLL = new UsuariosBLL();
            Usuario usuario = oBLL.Retrieve(id);

            return View(usuario);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usuario usuario, HttpPostedFileBase upFile)
        {
            ActionResult Result;
            try
            {

                Usuario tmpusuario = null;
                UsuariosBLL oBLL = new UsuariosBLL();

                if (ModelState.IsValid)
                {

                    tmpusuario = oBLL.Retrieve(usuario.UsuarioID);
                    tmpusuario.UserName = usuario.UserName;
                    tmpusuario.Rol = usuario.Rol;
                    tmpusuario.Nombres = usuario.Nombres;
                    tmpusuario.ApellidoMaterno = usuario.ApellidoMaterno;
                    tmpusuario.ApellidoPaterno = usuario.ApellidoPaterno;
                    tmpusuario.Contraseña = usuario.Contraseña;
                    tmpusuario.Sexo = usuario.Sexo;
                    tmpusuario.Ocupacion = usuario.Ocupacion;
                    tmpusuario.Carrera = usuario.Carrera;
                    tmpusuario.Descripción = usuario.Descripción;
                    tmpusuario.Correo = usuario.Correo;
                    tmpusuario.Estatus = usuario.Estatus;
                    Global.suces = 1;

                    if (upFile != null && upFile.ContentLength > 0)
                    {
                        int tamaño = upFile.ContentLength;
                        byte[] buffer = new byte[tamaño];
                        upFile.InputStream.Read(buffer, 0, tamaño);
                        tmpusuario.Foto = buffer;
                    }
                    else
                    {

                        tmpusuario.Foto = null;
                    }
                    oBLL.Update(tmpusuario);
                    Result = RedirectToAction("Details", new { id = usuario.UsuarioID });
                }
                else
                {
                    Result = RedirectToAction("Details", new { id = usuario.UsuarioID });
                }
                return Result;
            }
            catch (Exception e)
            {
                return View(usuario);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPerfilContraEstatus(Usuario usuario)
        {
            ActionResult Result;
            try
            {

                Usuario tmpusuario = null;
                UsuariosBLL oBLL = new UsuariosBLL();

                if (ModelState.IsValid)
                {

                    tmpusuario = oBLL.Retrieve(usuario.UsuarioID);
                    tmpusuario.UserName = usuario.UserName;
                    tmpusuario.Rol = usuario.Rol;
                    tmpusuario.Nombres = usuario.Nombres;
                    tmpusuario.ApellidoMaterno = usuario.ApellidoMaterno;
                    tmpusuario.ApellidoPaterno = usuario.ApellidoPaterno;
                    tmpusuario.Contraseña = usuario.Contraseña;
                    tmpusuario.Sexo = usuario.Sexo;
                    tmpusuario.Ocupacion = usuario.Ocupacion;
                    tmpusuario.Carrera = usuario.Carrera;
                    tmpusuario.Descripción = usuario.Descripción;
                    tmpusuario.Correo = usuario.Correo;
                    tmpusuario.Estatus = usuario.Estatus;
                    tmpusuario.Foto = usuario.Foto;

                    oBLL.Update(tmpusuario);
                    Global.suces = 1;
                    Result = RedirectToAction("Details", new { id = usuario.UsuarioID });
                }
                else
                {
                    Result = RedirectToAction("Details", new { id = usuario.UsuarioID });
                    Global.suces = 0;
                }
                return Result;
            }
            catch (Exception e)
            {
                return View(usuario);
            }
        }




        public ActionResult Details(int id)
        {
            UsuariosBLL oBLL = new UsuariosBLL();
            Usuario usuario = oBLL.Retrieve(id);
            if (Global.suces == 1)
            {
                ViewBag.success = 1;
            }
            else
            {
                ViewBag.success = 0;
            }
            Global.suces = 0;

            return View(usuario);
        }

        public ActionResult Delete(int id)
        {

            UsuariosBLL oBLL = new UsuariosBLL();
            oBLL.Delete(id);
            return Redirect(Url.Action("Login", "Account"));
        }

        public FileStreamResult GetImage(int id)
        {
            UsuariosBLL oBLL = new UsuariosBLL();
            Usuario usuario = oBLL.Retrieve(id);
            var bytes = usuario.Foto;
            return File(new MemoryStream(bytes, 0, bytes.Length), "image/jpeg");
        }

        public FileStreamResult Getknowimage(int id)
        {
            UsuariosBLL oBLL = new UsuariosBLL();
            Usuario usuario = oBLL.Retrieve(id);
            var bytes = usuario.Foto;
            var nuled = new byte[] { 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20 };
            if (bytes != null)
            {
                return File(new MemoryStream(bytes, 0, bytes.Length), "image/jpeg");
            }
            else
            {
                return File(new MemoryStream(nuled, 0, 0), "image/jpeg");
            }

        }

    }
}

web_application/Views/Preguntas/Delete.cshtml
@model Entities.Pregunta

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pregunta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Usuario.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TituloPregunta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TituloPregunta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContenidoPregunta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContenidoPregunta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

web_application/Views/Preguntas/Details.cshtml
@model Entities.Pregunta


@{
    ViewBag.Title = "Details";
}

<div class="portlet-body">
    <div class="row">
        <div class="col-md-12 col-sm-4">
            <div class="todo-tasklist">
                <div class="todo-tasklist-item todo-tasklist-item-border-green">
                    <img alt="foto" width="50px" height="50px" class="todo-userpic pull-left" src="@Url.Action("Getknowimage", "Usuario", new { id = Model.UsuarioID  })" />
                    @*<img class="todo-userpic pull-left" src="../assets/pages/media/users/avatar4.jpg" width="27px" height="27px">*@
                    <div class="todo-tasklist-item-title"><h1> @Html.Action("Getusuario", new { id = Model.UsuarioID })</h1> </div>
                    <div class="todo-tasklist-item-text"><h2>  @Html.DisplayFor(modelItem => Model.ContenidoPregunta) </h2> </div>
                    <div class="todo-tasklist-item-text"><h5>  @Html.Action("ShowTemas", "Preguntas") </h5> </div>
                    <div class="todo-tasklist-controls pull-left">
                        <span class="todo-tasklist-date">
                            @{

                                String newfecha = "";
                                int c = 0;
                                String value = (Model.Creada).ToString();
                                Char delimiter = ' ';
                                String[] substrings = value.Split(delimiter);
                                foreach (var substring in substrings)
                                {
                                    if (c == 0)
                                    {
                                        newfecha = substring;
                                    }
                                    c++;

                                }

                            }
                            <i class="fa fa-calendar"></i> @newfecha
                        </span>
                        <span class="todo-tasklist-badge badge badge-roundless"> @Html.DisplayFor(modelItem => Model.TituloPregunta)</span>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*<div>
        <h4>Pregunta</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UsuarioID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UsuarioID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TituloPregunta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TituloPregunta)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContenidoPregunta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContenidoPregunta)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Estado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Estado)
            </dd>

        </dl>
    </div>*@
<div id="up">
    @Html.Action("ShowRespuestas", "Preguntas")
</div>
<div class="row">
    <div class="col-md-12">
        <div id="DetOrd">

        </div>
    </div>
</div>

<div>
    @Html.Partial("_CreateRespuesta", new Entities.Respuesta())
</div>



@section Styles{

    <link href="~/Content/datatables.bootstrap.css" rel="stylesheet" />
    <link href="~/Content/datatables.min.css" rel="stylesheet" />
    <link href="~/Content/select2.css" rel="stylesheet" />
    <link href="~/Content/select2-bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/todo-2.min.css" rel="stylesheet" />

}

<!-- instala en  nuget -->
@section Scripts{

    <script src="~/Scripts/todo-2.min.js"></script>
    <script src="~/Scripts/select2.full.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
    <script src="~/Scripts/datatable.js" type="text/javascript"></script>
    <script src="~/Scripts/datatables.min.js" type="text/javascript"></script>
    <script src="~/Scripts/datatables.bootstrap.js" type="text/javascript"></script>
    <script src="~/Scripts/table-datatables-responsive.min.js"></script>

    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script>




        function cerrar() {
            $('#up').hide(); //oculto mediante id

        }
        function error() {
            alert('Se ha producido un error');

        }


    </script>

    <script type="text/javascript">

        //FECHA
        $(document).ready(function () {
            Date.prototype.yyyymmdd = function () {
                var yyyy = this.getFullYear().toString();
                var mm = (this.getMonth() + 1).toString(); // getMonth() is zero-based
                var dd = this.getDate().toString();
                return yyyy + "/" + (mm[1] ? mm : "0" + mm[0]) + "/" + (dd[1] ? dd : "0" + dd[0]); // padding
            };
            var date = new Date();
            $("#fecha").val(date.yyyymmdd());
        });

    </script>
}

web_application/Views/Preguntas/Edit.cshtml
@model Entities.Pregunta
@using System.Security.Claims;
@using System.Threading;
@{
    //AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.Email;
    AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.NameIdentifier;
    var Usuario = "";
    var ID = "";
    ClaimsPrincipal Principal = Thread.CurrentPrincipal as ClaimsPrincipal;
    if (Principal != null && Principal.Identity.IsAuthenticated)
    {
        var Claims = Principal.Claims.ToList();
        Usuario = Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name).Value;
        ID = Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;
    }


}
@{
    ViewBag.Title = "Edit";
}


<div class="portlet-body">
    <div class="row">
        <div class="col-md-7 col-sm-8">
            @using (Html.BeginForm("Edit", "Preguntas", null, FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <!-- TASK HEAD -->

                @*Usuario ID*@
                <div class="form-group" style='display:none;'>
                    @Html.EditorFor(model => model.UsuarioID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UsuarioID, "", new { @class = "text-danger" })

                    @Html.EditorFor(model => model.PreguntaID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PreguntaID, "", new { @class = "text-danger" })

                   
                </div>
                <div class="form">
                    <div class="form-group">
                        <div class="col-md-8 col-sm-8">
                            <div class="todo-taskbody-user">
                                @*@Html.Action("Getknowimage","Usuario", new { id = @ID })*@
                                <img alt="foto" width="50px" height="50px" class="todo-userpic pull-left" src="@Url.Action("Getknowimage", "Usuario", new { id = @ID,  })" />
                                @*<img class="todo-userpic pull-left" src="../assets/pages/media/users/avatar6.jpg" width="50px" height="50px">*@
                                <span class="todo-username pull-left">@Usuario</span>
                                @*<button type="button" class="todo-username-btn btn btn-circle btn-default btn-sm">&nbsp;edit&nbsp;</button>*@
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4">
                            <div class="todo-taskbody-date pull-right">
                                @(Html.ActionLink("Cancelar", "Index", new { id = 1 }, new { @class = "todo-username-btn btn btn-circle btn-default btn-sm" }))
                                @*<button type="button" class="todo-username-btn btn btn-circle btn-default btn-sm">&nbsp; Complete &nbsp;</button>*@
                            </div>
                        </div>
                    </div>
                    <!-- END TASK HEAD -->
                    <!-- TASK TITLE -->
                    <label class="control label"> Estatus</label>
                    <div class="form-group">
                       
                        <div class="col-md-12">
                           
                            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control todo-taskbody-tasktitle", placeholder = "Titulo" } })
                            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.TituloPregunta, new { htmlAttributes = new { @class = "form-control todo-taskbody-tasktitle", placeholder = "Titulo" } })
                            @Html.ValidationMessageFor(model => model.TituloPregunta, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- TASK DESC -->
                    <div class="form-group">
                        <div class="col-md-12">
                            @*<textarea class="form-control todo-taskbody-taskdesc" rows="8" placeholder="Task Description..."></textarea>*@
                            @Html.TextAreaFor(model => model.ContenidoPregunta, new { @class = "form-control todo-taskbody-taskdesc", rows = "8", placeholder = "¿Que quieres preguntar?" })
                            @Html.ValidationMessageFor(model => model.ContenidoPregunta, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- END TASK DESC -->
                    <!-- TASK DUE DATE -->
                    <div class="form-group" style='display:none;'>
                        <div class="col-md-12">
                            <div class="input-icon">
                                <i class="fa fa-calendar"></i>
                                @Html.EditorFor(model => model.Creada, new { htmlAttributes = new { id = "fecha", @class = "", placeholder = "Fecha" } })
                                @Html.ValidationMessageFor(model => model.Creada, "", new { @class = "text-danger" })
                                @*<input type="text" class="form-control todo-taskbody-due" placeholder="Due Date...">*@
                            </div>
                        </div>
                    </div>
                    <!-- TASK TAGS TEMAS/////////////////////////////////////EN ESPERA -->
                    @*<div class="form-group">
                            <div class="col-md-12">
                                <select class="form-control todo-taskbody-tags">
                                    <option value="Pending">Pending</option>
                                    <option value="Completed">Completed</option>
                                    <option value="Testing">Testing</option>
                                    <option value="Approved">Approed</option>
                                    <option value="Rejected">Rejected</option>
                                </select>
                            </div>
                        </div>*@
                    <!-- TASK TAGS -->
                    <div class="form-actions right todo-form-actions">
                        <button type="submit" class="btn green-sharp btn-circle">Actualizar</button>
                        @*@Html.ActionLink("Cancelar", "Pregunta", new { htmlAttributes = new { @class = "btn btn-circle btn-sm btn-default" } })*@
                        @*<button class="btn btn-circle btn-sm btn-default">Cancel</button>*@
                    </div>
                </div>


            }
        </div>
    </div>
</div>


@section Styles{


    <link href="~/Content/select2.css" rel="stylesheet" />
    <link href="~/Content/select2-bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/todo-2.min.css" rel="stylesheet" />

}

@section Scripts {

    <script src="~/Scripts/bootstrap-confirmation.min.js"></script>
    <script src="~/Scripts/ui-confirmations.min.js"></script>
    <script type="text/javascript">

        //FECHA


    </script>
}

web_application/Views/Preguntas/_ShowTemas.cshtml
@model IEnumerable<Entities.PreguntaTema>


@foreach (var item in Model) {
 
            @Html.Action("GetTema", "Preguntas", new { id = item.TemaID })
   
}